build:
    nodes:
        tests:
            environment:
                sdkman:
                    - java
                    - maven
                timezone: FR

            services:
                mysql: 5.7

            tests:
                override:
                    - command: mysql -u root -e "create database araknemu"
                    - command: mysql -u root -e "create user araknemu@127.0.0.1"
                    - command: mysql -u root -e "grant all privileges on araknemu.* to araknemu@127.0.0.1"
                    - command: mvn clean package
                      #                    - coverage:
                      #  file: 'target/site/jacoco'
                      #  format: 'jacoco'
